### ISSUE TITLE
why some modulename like this "modulename: system@framework@boot.oat", 

### ISSUE THREAD

**Issue by buchisu** [deathmemory/fridaRegstNtv#15]
==== class: J.N ====
==== methods: 0x12008820 nMethods: 136 ====
[INFO][fridaRegstNtv]: name: M$lotPPc, signature: (I)V, fnPtr: 0xd67f8074, modulename: system@framework@boot.oat -> base: 0x6ff84000, offset: 0x66874074
[INFO][fridaRegstNtv]: name: Mcaj_8qf, signature: ()I, fnPtr: 0xd67f803c, modulename: system@framework@boot.oat -> base: 0x6ff84000, offset: 0x6687403c
[INFO][fridaRegstNtv]: name: M1UV95tj, signature: ()J, fnPtr: 0xba163fc4, modulename: system@framework@boot.oat -> base: 0x6ff84000, offset: 0x4a1dffc4

**Comment by deathmemory** [comment]
你是不是用的模拟器？

**Comment by buchisu** [comment]
> 你是不是用的模拟器？

是的，用模拟器就是显示成boot.oat吗?

**Comment by deathmemory** [comment]
> > 你是不是用的模拟器？
> 
> 是的，用模拟器就是显示成boot.oat吗?

嗯模拟器会出这个问题，能不用模拟器就不用模拟器吧
